Repository UQdeco2800/2022-studio-1, pull requests merged in 2022-09, with the labels that each got.

#111 Team 9 day night config
  source/core/assets/configs/DayNight.json
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
  source/core/src/main/com/deco2800/game/services/configs/DayNightCycleConfig.java
Labels: Team 9

#112 Loading config file and begining implementation of core functions
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
Labels: Team 9

#119 Team 9 day night cycle service
  source/core/assets/configs/DayNight.json
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
  source/core/src/main/com/deco2800/game/services/configs/DayNightCycleConfig.java
Labels: Team 9

#125 Team9 day night cycle status plus back unittests
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
  source/core/src/test/com/deco2800/game/services/DayNightCycleServiceTest.java
Labels: Team 9

#127 Team 9 day night cycle pause
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
  source/core/src/test/com/deco2800/game/services/DayNightCycleServiceTest.java
Labels: Team 9

#135 Team9 day night filter
  source/core/assets/configs/DayNight.json
  source/core/assets/shaders/base.vert
  source/core/assets/shaders/light.frag
  source/core/src/main/com/deco2800/game/AtlantisSinks.java
  source/core/src/main/com/deco2800/game/rendering/DayNightCycleComponent.java
  source/core/src/main/com/deco2800/game/rendering/RenderService.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/services/ServiceLocator.java
Labels: Team 9

#134 Team 9 day night cycle service
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
  source/core/src/test/com/deco2800/game/services/DayNightCycleServiceTest.java
Labels: Team 9

#136 Ability to toggle day night cycle VFX by pressing PERIOD key #128
  source/core/src/main/com/deco2800/game/rendering/DayNightCycleComponent.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: Team 9

#139 Get terrain batch to use day night cycle shader as well #128
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/deco2800/game/rendering/RenderService.java
Labels: Team 9

#147 Team9 day night cycle service fix threading bug
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
  source/core/src/test/com/deco2800/game/services/DayNightCycleServiceTest.java
Labels: Team 9

#159 Added logic to pause and resume methods of the MainGameScreen for day/night cycle
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
Labels: Team 9

#173 Fix bug causing incorrect sequence of days and also 0th day to be ret…
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
  source/core/src/test/com/deco2800/game/services/DayNightCycleServiceTest.java
Labels: bug, Team 9

#184 add wiki UML images for day night cycle feature
  assets/wiki/daynightcycle-component.png
  assets/wiki/daynightcycle-service.png
Labels: documentation, Team 9

#185 updated DayNightCycleService UML - removing overlapping text
  assets/wiki/daynightcycle-service.png
Labels: documentation, Team 9

#187 Team9 daynightcycle component unit tests
  source/core/src/main/com/deco2800/game/rendering/DayNightCycleComponent.java
  source/core/src/test/com/deco2800/game/rendering/DayNightCycleComponentTest.java
Labels: Team 9

#191 Team9 clock service update
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
  source/core/src/main/com/deco2800/game/services/DayNightCycleStatus.java
  source/core/src/test/com/deco2800/game/services/DayNightCycleServiceTest.java
Labels: Team 9

#192 bug fixes and fixing tests #128
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
  source/core/src/test/com/deco2800/game/services/DayNightCycleServiceTest.java
Labels: Team 9

#199 Team 9 Clock UI Element
  source/core/assets/images/clock.png
  source/core/assets/images/clock_sprites/clock_boss.png
  source/core/assets/images/clock_sprites/clock_day1_1.png
  source/core/assets/images/clock_sprites/clock_day1_2.png
  source/core/assets/images/clock_sprites/clock_day1_3.png
  source/core/assets/images/clock_sprites/clock_day1_4.png
  source/core/assets/images/clock_sprites/clock_day1_5.png
  source/core/assets/images/clock_sprites/clock_day1_6.png
  source/core/assets/images/clock_sprites/clock_day1_7.png
  source/core/assets/images/clock_sprites/clock_day1_8.png
  source/core/assets/images/clock_sprites/clock_day2_1.png
  source/core/assets/images/clock_sprites/clock_day2_2.png
  source/core/assets/images/clock_sprites/clock_day2_3.png
  source/core/assets/images/clock_sprites/clock_day2_4.png
  source/core/assets/images/clock_sprites/clock_day2_5.png
  source/core/assets/images/clock_sprites/clock_day2_6.png
  source/core/assets/images/clock_sprites/clock_day2_7.png
  source/core/assets/images/clock_sprites/clock_day2_8.png
  source/core/assets/images/clock_sprites/clock_day3_1.png
  source/core/assets/images/clock_sprites/clock_day3_2.png
  source/core/assets/images/clock_sprites/clock_day3_3.png
  source/core/assets/images/clock_sprites/clock_day3_4.png
  source/core/assets/images/clock_sprites/clock_day3_5.png
  source/core/assets/images/clock_sprites/clock_day3_6.png
  source/core/assets/images/clock_sprites/clock_day3_7.png
  source/core/assets/images/clock_sprites/clock_day3_8.png
  source/core/assets/images/clock_sprites/clock_day4_1.png
  source/core/assets/images/clock_sprites/clock_day4_2.png
  source/core/assets/images/clock_sprites/clock_day4_3.png
  source/core/assets/images/clock_sprites/clock_day4_4.png
  source/core/assets/images/clock_sprites/clock_day4_5.png
  source/core/assets/images/clock_sprites/clock_day4_6.png
  source/core/assets/images/clock_sprites/clock_day4_7.png
  source/core/assets/images/clock_sprites/clock_day4_8.png
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/DayNightClockComponent.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
  source/core/src/main/com/deco2800/game/services/ServiceLocator.java
  source/core/src/test/com/deco2800/game/services/DayNightCycleServiceTest.java
Labels: task, Team 9

#200 Story line screens
  source/core/src/main/com/deco2800/game/components/storyline/StoryLineDisplay.java
Labels: Team 2

#202 Story line screens
  source/core/assets/images/StoryLine/Textbox 2 (thicker).png
Labels: Team 2

#203 First night screen
  source/core/assets/test/files/atlantisBasicBackground.png
  source/core/assets/test/files/clearBackground.png
  source/core/src/main/com/deco2800/game/AtlantisSinks.java
  source/core/src/main/com/deco2800/game/components/firstnight/FirstNightActions.java
  source/core/src/main/com/deco2800/game/components/firstnight/FirstNightDisplay.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameActions.java
  source/core/src/main/com/deco2800/game/screens/FirstNightScreen.java
Labels: Team 2

#204 Story line screens
  source/core/assets/images/StoryLine/FirstNight.png
  source/core/assets/images/StoryLine/prologue1.png
  source/core/assets/images/StoryLine/prologue2.png
  source/core/assets/images/StoryLine/prologue3.png
  source/core/assets/images/StoryLine/prologue4.png
  source/core/assets/images/StoryLine/storylineBackground.png
  source/core/assets/images/StoryLine/storylineBackground1.png
  source/core/assets/images/StoryLine/storylineBackground2.png
  source/core/assets/images/StoryLine/storylineBackground3.png
  source/core/src/main/com/deco2800/game/components/storyline/frames/prologue1.java
  source/core/src/main/com/deco2800/game/components/storyline/frames/prologue2.java
  source/core/src/main/com/deco2800/game/components/storyline/frames/prologue3.java
  source/core/src/main/com/deco2800/game/components/storyline/frames/prologue4.java
  source/core/src/main/com/deco2800/game/screens/StoryLineScreen.java
Labels: Team 2

#231 Story line screens
  source/core/assets/images/StoryLine/SL_1.png
  source/core/assets/images/StoryLine/SL_2.png
  source/core/assets/images/StoryLine/SL_3.png
  source/core/src/main/com/deco2800/game/AtlantisSinks.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameActions.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/deco2800/game/components/storyline/StoryLineActions.java
  source/core/src/main/com/deco2800/game/components/storyline/StoryLineLinkedList.java
  source/core/src/main/com/deco2800/game/components/storyline/epilogue/Frame.java
  source/core/src/main/com/deco2800/game/components/storyline/epilogue/epilogue1.java
  source/core/src/main/com/deco2800/game/components/storyline/epilogue/epilogue2.java
  source/core/src/main/com/deco2800/game/components/storyline/epilogue/epilogue3.java
  source/core/src/main/com/deco2800/game/components/storyline/epilogueDisplay.java
  source/core/src/main/com/deco2800/game/components/storyline/prologue/Frame.java
  source/core/src/main/com/deco2800/game/components/storyline/prologue/prologue1.java
  source/core/src/main/com/deco2800/game/components/storyline/prologue/prologue2.java
  source/core/src/main/com/deco2800/game/components/storyline/prologue/prologue3.java
  source/core/src/main/com/deco2800/game/components/storyline/prologue/prologue4.java
  source/core/src/main/com/deco2800/game/components/storyline/prologueDisplay.java
  source/core/src/main/com/deco2800/game/components/storyline/storyLineAction.java
  source/core/src/main/com/deco2800/game/components/storyline/storyLineInputComponent.java
  source/core/src/main/com/deco2800/game/input/KeyboardInputFactory.java
  source/core/src/main/com/deco2800/game/screens/EpilogueScreen.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/PrologueScreen.java
Labels: Team 2

#262 create core data classes for achievements in preparation for persiste…
  source/core/src/main/com/deco2800/game/achievements/Achievement.java
  source/core/src/main/com/deco2800/game/achievements/AchievementType.java
Labels: Team 9

#264 Fixed triggering of EVENT_INTERMITTENT_PART_OF_DAY_CLOCK
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/DayNightClockComponent.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
Labels: Team 9

#266 Added achievements to achievement factory
  source/core/src/main/com/deco2800/game/achievements/AchievementFactory.java
Labels: Team 9

#273 Team 9 achievement handler
  source/core/src/main/com/deco2800/game/AtlantisSinks.java
  source/core/src/main/com/deco2800/game/achievements/Achievement.java
  source/core/src/main/com/deco2800/game/achievements/AchievementData.java
  source/core/src/main/com/deco2800/game/achievements/AchievementFactory.java
  source/core/src/main/com/deco2800/game/components/player/InventoryComponent.java
  source/core/src/main/com/deco2800/game/components/player/PlayerActions.java
  source/core/src/main/com/deco2800/game/entities/factories/CrystalFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/ResourceBuildingFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/StructureFactory.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
  source/core/src/main/com/deco2800/game/services/ServiceLocator.java
Labels: task, Team 9

#285 disabled epilogue listener and reset crystal health to 1000
  source/core/assets/configs/crystal.json
  source/core/src/main/com/deco2800/game/components/maingame/MainGameActions.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: Team 2
