Repository UQdeco2800/2022-studio-1, pull requests merged in 2022-10, with the labels that each got.

#288 Team9 achievements popup
  source/core/assets/images/achievements/Building_64x64_Icon.png
  source/core/assets/images/achievements/Game_64x64_Icon.png
  source/core/assets/images/achievements/Kill_64x64_Icon.png
  source/core/assets/images/achievements/Misc_64x64_Icon.png
  source/core/assets/images/achievements/Notification_Popup.png
  source/core/assets/images/achievements/Notification_Popup_scaled.png
  source/core/assets/images/achievements/Resource_64x64_Icon.png
  source/core/assets/images/achievements/Upgrade_64x64_Icon.png
  source/core/src/main/com/deco2800/game/achievements/AchievementFactory.java
  source/core/src/main/com/deco2800/game/achievements/AchievementType.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementPopupComponent.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameTutorials.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: Team 9

#291 Team 9 achievement icon fix
  source/.gitignore
  source/core/assets/Achievements/Building_Icon.png
  source/core/assets/Achievements/Game_Icon.png
  source/core/assets/Achievements/Misc_Icon.png
  source/core/assets/Achievements/Upgrade_Icon.png
  source/core/assets/images/achievements/Background_Box.png
  source/core/assets/images/achievements/Badge_Background_Box.png
  source/core/assets/images/achievements/Badge_Description_Box.png
  source/core/assets/images/achievements/Building_Icon.png
  source/core/assets/images/achievements/Game_Icon.png
  source/core/assets/images/achievements/Kills_Icon.png
  source/core/assets/images/achievements/Misc_Icon.png
  source/core/assets/images/achievements/Resourse_Icon.png
  source/core/assets/images/achievements/Tab_Box.png
  source/core/assets/images/achievements/Tick_Icon.png
  source/core/assets/images/achievements/Upgrade_Icon.png
Labels: bug, Team 9

#293 Added ability to get an achievement by its id
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
Labels: Team 9

#294 Team 9 achievement screen
  source/core/assets/Achievements/AchievementsList.txt
  source/core/assets/images/achievements/AchievementsTitle.png
  source/core/assets/images/achievements/Background_1348x888_Box.png
  source/core/assets/images/achievements/Background_1664x824_Box.png
  source/core/assets/images/achievements/Badge_Background_1904x908_Box.png
  source/core/assets/images/achievements/Badge_Background_2540x1033_Box.png
  source/core/assets/images/achievements/Badge_Description_1580x126_Box.png
  source/core/assets/images/achievements/Tab_428x824_Box.png
  source/core/assets/images/achievements/summaryIcon.png
  source/core/src/main/com/deco2800/game/AtlantisSinks.java
  source/core/src/main/com/deco2800/game/achievements/AchievementType.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementActions.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementDisplay.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameActions.java
  source/core/src/main/com/deco2800/game/screens/AchievementScreen.java
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
Labels: feature

#296 Added tests for achievement handler
  source/core/assets/test/files/testAchievements.json
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
  source/core/src/test/com/deco2800/game/services/AchievementHandlerTest.java
Labels: Team 9

#298 first working revision of achievement cards displaying #267
  source/core/assets/images/achievements/achievement_card_completed.png
  source/core/assets/images/achievements/achievement_card_locked_n.png
  source/core/assets/images/achievements/milestone_1_completed.png
  source/core/assets/images/achievements/milestone_1_incomplete.png
  source/core/assets/images/achievements/milestone_2_completed.png
  source/core/assets/images/achievements/milestone_2_incomplete.png
  source/core/assets/images/achievements/milestone_3_completed.png
  source/core/assets/images/achievements/milestone_3_incomplete.png
  source/core/assets/images/achievements/milestone_4_completed.png
  source/core/assets/images/achievements/milestone_4_incomplete.png
  source/core/src/main/com/deco2800/game/achievements/AchievementFactory.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementDisplay.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
Labels: Team 9

#310 Team 9 achievement screen
  source/core/assets/images/achievements/Background.png
  source/core/assets/images/achievements/Background_2540x1033.png
  source/core/assets/images/achievements/BadgeBackground_1664x824.png
  source/core/assets/images/achievements/BadgeContent_Box.png
  source/core/assets/images/achievements/Summary_Button.png
  source/core/assets/images/achievements/Tab_Background_Box.png
  source/core/src/main/com/deco2800/game/achievements/AchievementType.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementDisplay.java
  source/core/src/main/com/deco2800/game/screens/AchievementScreen.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
Labels: Team 9

#314 Story line screens
  source/core/assets/images/StoryLine/Artboard 1.png
  source/core/assets/images/StoryLine/DefeatScreen.png
  source/core/assets/images/StoryLine/DefeatScreenFinal.png
  source/core/assets/images/StoryLine/First night scene.png
  source/core/assets/images/StoryLine/VictoryScreen.png
  source/core/assets/images/StoryLine/VictoryScreen1920.png
  source/core/assets/images/StoryLine/VictoryScreenWithSpace.png
  source/core/assets/images/StoryLine/WinScreenFinal.png
  source/core/assets/images/StoryLine/night 2.png
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/firstnight/FirstNightActions.java
  source/core/src/main/com/deco2800/game/components/maingame/EpilogueLayover.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameActions.java
  source/core/src/main/com/deco2800/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/components/storyline/epilogueDisplay.java
  source/core/src/main/com/deco2800/game/components/storyline/prologueDisplay.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/PrologueScreen.java
Labels: Team 2

#348 Team 9 achievement boss n buy
  source/core/src/main/com/deco2800/game/achievements/Achievement.java
  source/core/src/main/com/deco2800/game/achievements/AchievementFactory.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/maingame/EpilogueLayover.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/deco2800/game/components/shop/ShopArtefactDisplay.java
  source/core/src/main/com/deco2800/game/components/shop/ShopBuildingDisplay.java
  source/core/src/main/com/deco2800/game/components/shop/ShopEquipmentDisplay.java
  source/core/src/main/com/deco2800/game/screens/MainMenuScreen.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
  source/core/src/test/com/deco2800/game/services/AchievementHandlerTest.java
Labels: Team 9

#349 Story line screens
  source/core/src/main/com/deco2800/game/components/maingame/EpilogueLayover.java
  source/core/src/main/com/deco2800/game/entities/factories/NPCFactory.java
Labels: Team 10

#351 Added textures to achievementTextures
  source/core/src/main/com/deco2800/game/screens/AchievementScreen.java
Labels: Team 9

#353 Streamlined end of game triggers for achievements
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/maingame/EpilogueLayover.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
Labels: Team 9

#355 Team 9 clock bug fix
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
Labels: bug, Team 9

#359 Team9 guidebook and building achievements
  source/core/assets/configs/buildings/quarry.json
  source/core/src/main/com/deco2800/game/achievements/Achievement.java
  source/core/src/main/com/deco2800/game/achievements/AchievementFactory.java
  source/core/src/main/com/deco2800/game/components/Guidebook/GuidebookActions.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementPopupComponent.java
  source/core/src/main/com/deco2800/game/entities/StructureService.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
Labels: Team 9

#363 Team 9 achievements UI assets
  source/core/assets/images/achievements/Building_NotCurrent.png
  source/core/assets/images/achievements/Game_NotCurrent.png
  source/core/assets/images/achievements/Kills_NotCurrent.png
  source/core/assets/images/achievements/Misc_NotCurrent.png
  source/core/assets/images/achievements/Resources_NotCurrent.png
  source/core/assets/images/achievements/Summary_NotCurrent.png
  source/core/assets/images/achievements/Upgrade_NotCurrent.png
Labels: Team 9

#368 Team9 achievements UI assets
  source/core/assets/images/achievements/Building_NotCurrent.png
  source/core/assets/images/achievements/Game_NotCurrent.png
  source/core/assets/images/achievements/Kills_NotCurrent.png
  source/core/assets/images/achievements/Misc_NotCurrent.png
  source/core/assets/images/achievements/Resources_NotCurrent.png
  source/core/assets/images/achievements/Summary_NotCurrent.png
  source/core/assets/images/achievements/Upgrade_NotCurrent.png
Labels: Team 9

#371 Achievement stat
  source/core/src/main/com/deco2800/game/components/maingame/EpilogueLayover.java
  source/core/src/main/com/deco2800/game/components/shop/ShopEquipmentDisplay.java
  source/core/src/main/com/deco2800/game/rendering/DayNightCycleComponent.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
  source/core/src/test/com/deco2800/game/rendering/DayNightCycleComponentTest.java
Labels: Team 9

#373 Team 9 achievements
  source/core/src/main/com/deco2800/game/achievements/Achievement.java
  source/core/src/main/com/deco2800/game/achievements/AchievementFactory.java
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementDisplay.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
  source/core/src/test/com/deco2800/game/services/AchievementHandlerTest.java
Labels: task, Team 9

#374 Day/night cycle display fixes
  source/core/src/main/com/deco2800/game/components/DayNightClockComponent.java
  source/core/src/main/com/deco2800/game/rendering/DayNightCycleComponent.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
Labels: Team 9

#375 Team 9 achievement screen
  source/core/assets/images/achievements/Buildings_Icon.png
  source/core/assets/images/achievements/Buildings_NotCurrent.png
  source/core/assets/images/achievements/Kills_Icon.png
  source/core/assets/images/achievements/Resources_Icon.png
  source/core/assets/images/achievements/Summary_Icon.png
  source/core/assets/images/achievements/Upgrades_Icon.png
  source/core/assets/images/achievements/Upgrades_NotCurrent.png
  source/core/assets/images/achievements/summaryIcon.png
  source/core/src/main/com/deco2800/game/achievements/AchievementType.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementActions.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementButton.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementDisplay.java
  source/core/src/main/com/deco2800/game/screens/AchievementScreen.java
Labels: Team 9

#388 Added new badge backgrounds for resources and upgrade achievements
  source/core/assets/images/achievements/Resources_Lock.png
  source/core/assets/images/achievements/Resources_Tick.png
  source/core/assets/images/achievements/Upgrade_Lock.png
  source/core/assets/images/achievements/Upgrade_Tick.png
Labels: Team 9

#397 Team 9 achievement screen
  source/core/assets/images/achievements/Buildings_Icon.png
  source/core/assets/images/achievements/Buildings_NotCurrent.png
  source/core/assets/images/achievements/Game_Icon.png
  source/core/assets/images/achievements/Game_NotCurrent.png
  source/core/assets/images/achievements/Kills_Icon.png
  source/core/assets/images/achievements/Kills_NotCurrent.png
  source/core/assets/images/achievements/Misc_Icon.png
  source/core/assets/images/achievements/Misc_NotCurrent.png
  source/core/assets/images/achievements/Resources_Icon.png
  source/core/assets/images/achievements/Resources_Lock.png
  source/core/assets/images/achievements/Resources_NotCurrent.png
  source/core/assets/images/achievements/Resources_Tick.png
  source/core/assets/images/achievements/Summary_Icon.png
  source/core/assets/images/achievements/Summary_NotCurrent.png
  source/core/assets/images/achievements/Upgrade_Lock.png
  source/core/assets/images/achievements/Upgrade_Tick.png
  source/core/assets/images/achievements/Upgrades_Icon.png
  source/core/assets/images/achievements/Upgrades_Lock.png
  source/core/assets/images/achievements/Upgrades_NotCurrent.png
  source/core/assets/images/achievements/Upgrades_Tick.png
  source/core/src/main/com/deco2800/game/AtlantisSinks.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementActions.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementInterface.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameActions.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameInterface.java
  source/core/src/main/com/deco2800/game/components/shop/ShopInterface.java
  source/core/src/main/com/deco2800/game/screens/AchievementScreen.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: feature, Team 9

#399 Code smell fixes
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameTutorials.java
  source/core/src/main/com/deco2800/game/entities/configs/EnemyConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/GhostKingConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/MeleeBossConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/deco2800/game/entities/factories/NPCFactory.java
  source/core/src/main/com/deco2800/game/services/DayNightCycleService.java
Labels: bug

#401 Code smell fixes
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/GuidebookArea.java
  source/core/src/main/com/deco2800/game/areas/terrain/IsoTileRenderer.java
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/Guidebook/GuidebookActions.java
  source/core/src/main/com/deco2800/game/components/Guidebook/GuidebookDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementInterface.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameActions.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameBuildingInterface.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameInterface.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameNpcInterface.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameTutorials.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/components/player/PlayerActions.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
Labels: bug

#400 move achievements save path to central game save folder
  source/core/src/main/com/deco2800/game/files/SaveGame.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
  source/core/src/test/com/deco2800/game/services/AchievementHandlerTest.java
Labels: Team 9

#408 Team9 achievement boxes
  source/core/assets/images/achievements/AchievementsTitle.png
  source/core/assets/images/achievements/Background_2540x1033.png
  source/core/assets/images/achievements/BadgeBackground_1664x824.png
  source/core/assets/images/achievements/Summary_Icon.png
  source/core/assets/images/achievements/Summary_NotCurrent.png
  source/core/src/main/com/deco2800/game/components/achievements/AchievementButton.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementInterface.java
  source/core/src/main/com/deco2800/game/ui/UIComponent.java
Labels: Team 9

#418 Team 9 achievement screen
  source/core/assets/images/achievements/Summary_Icon.png
  source/core/assets/images/achievements/Summary_NotCurrent.png
  source/core/assets/images/achievements/Tick_Icon.png
  source/core/src/main/com/deco2800/game/components/achievements/AchievementButton.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementInterface.java
Labels: Team 9

#420 Team 9 achievement screen
  source/core/src/main/com/deco2800/game/components/achievements/AchievementButton.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementInterface.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
Labels: Team 9

#426 Team 9 achievements edit
  source/core/src/main/com/deco2800/game/achievements/AchievementFactory.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementInterface.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
Labels: Team 9

#427 Fixed game music not stopping on returning to main menu
  source/core/src/main/com/deco2800/game/achievements/AchievementFactory.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameActions.java
Labels: bug

#428 UI interfaces: added guidebook music
  source/core/assets/replay_pid3261.log
  source/core/assets/sounds/GuidebookMusic.mp3
  source/core/assets/sounds/guideMusic.mp3
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/GuidebookArea.java
  source/core/src/main/com/deco2800/game/components/Guidebook/GuidebookActions.java
  source/core/src/main/com/deco2800/game/screens/MainMenuScreen.java
Labels: Team 10

#429 Team9 achievements progress bar
  source/core/src/main/com/deco2800/game/components/achievements/AchievementInterface.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementProgressBar.java
  source/core/src/main/com/deco2800/game/services/AchievementHandler.java
Labels: Team 9
